name: Pull Request Cleanup

on:
    pull_request:
        types: [closed]

jobs:
    branch_cleanup:
        name: Cleanup Branch
        runs-on: ubuntu-latest
        steps:
            - name: Message PR of Cleanup Successful
              uses: thollander/actions-comment-pull-request@main
              with:
                  message: "Temporary Environment Cleanup Complete"
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: Delete branch
              run: |
                    echo github.event.pull_request.base.ref: ${{ github.event.pull_request.base.ref }}
                    echo github.repository: ${{ github.repository }}
                    echo github.head_ref: ${{ github.head_ref }}
                #   curl -s -X DELETE -u username:${{secrets.GITHUB_TOKEN}} \
                #     "https://api.github.com/repos/${{ github.repository }}/git/refs/heads/${{ github.head_ref }}"
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
